Repository showMeTheMoneyPrac/BE_Repo, pull requests merged in 2022-05, with the labels that each got.

#5 issue-4
  src/main/java/com/shop/mall/domain/Cart.java
  src/main/java/com/shop/mall/domain/Img.java
  src/main/java/com/shop/mall/domain/Member.java
  src/main/java/com/shop/mall/domain/Orders.java
  src/main/java/com/shop/mall/domain/OrdersDetail.java
  src/main/java/com/shop/mall/domain/Product.java
  src/main/java/com/shop/mall/domain/ProductOption.java
  src/main/java/com/shop/mall/domain/Review.java
  src/main/java/com/shop/mall/domain/Timestamped.java
  src/test/java/com/shop/mall/service/MemberServiceTest.java
Labels: 📰 새 파일 생성

#46 Feature 36
  src/main/java/com/shop/mall/exception/ErrorCode.java
  src/main/java/com/shop/mall/repository/CartRepository.java
  src/main/java/com/shop/mall/repository/MemberRepository.java
  src/main/java/com/shop/mall/repository/OrdersDetailRepository.java
  src/main/java/com/shop/mall/repository/OrdersRepository.java
  src/main/java/com/shop/mall/service/MemberService.java
  src/main/java/com/shop/mall/validator/MemberValidator.java
Labels: 🐛bug, 🎨 코드 개선, 🐎 성능 향상

#48 🚑[fix] 포인트 사용 버그 해결
  src/main/java/com/shop/mall/service/OrdersService.java
Labels: 🐛bug

#50 Feature 47
  src/main/java/com/shop/mall/controller/ProductController.java
  src/main/java/com/shop/mall/domain/Product.java
  src/main/java/com/shop/mall/domain/Product1.java
  src/main/java/com/shop/mall/dto/ProductResponseDto.java
  src/main/java/com/shop/mall/repository/Product/ProductRepository.java
  src/main/java/com/shop/mall/service/ProductService.java
  src/test/java/com/shop/mall/service/ReviewServiceTest.java
Labels: 🎨 코드 개선, 🐎 성능 향상, 🔬 코드 범위 추가, 🤝 파일 병합

#51 중간배포mk2
  src/main/java/com/shop/mall/controller/DummyController.java
  src/main/java/com/shop/mall/controller/HealthController.java
  src/main/java/com/shop/mall/controller/ProductController.java
  src/main/java/com/shop/mall/domain/Member.java
  src/main/java/com/shop/mall/domain/Product.java
  src/main/java/com/shop/mall/domain/Product1.java
  src/main/java/com/shop/mall/dto/ProductResponseDto.java
  src/main/java/com/shop/mall/exception/ErrorCode.java
  src/main/java/com/shop/mall/exception/ErrorCodeException.java
  src/main/java/com/shop/mall/exception/ErrorCodeExceptionHandler.java
  src/main/java/com/shop/mall/exception/ErrorCodeResponse.java
  src/main/java/com/shop/mall/repository/CartRepository.java
  src/main/java/com/shop/mall/repository/ImgRepository.java
  src/main/java/com/shop/mall/repository/MemberRepository.java
  src/main/java/com/shop/mall/repository/OrdersDetailRepository.java
  src/main/java/com/shop/mall/repository/OrdersRepository.java
  src/main/java/com/shop/mall/repository/Product/ProductRepository.java
  src/main/java/com/shop/mall/repository/Product/ProductRepositoryCustom.java
  src/main/java/com/shop/mall/service/CartService.java
  src/main/java/com/shop/mall/service/MemberService.java
  src/main/java/com/shop/mall/service/OrdersService.java
  src/main/java/com/shop/mall/service/ProductService.java
  src/main/java/com/shop/mall/service/ReviewService.java
  src/main/java/com/shop/mall/validator/CartValidator.java
  src/main/java/com/shop/mall/validator/MemberValidator.java
  src/main/java/com/shop/mall/validator/OrdersDetailValidator.java
  src/main/java/com/shop/mall/validator/OrdersValidator.java
  src/main/java/com/shop/mall/validator/ProductValidator.java
  src/main/java/com/shop/mall/validator/ReviewValidator.java
  src/main/resources/static/index.html
  src/test/java/com/shop/mall/service/OrdersServiceTest.java
  src/test/java/com/shop/mall/service/ProductServiceTest.java
  src/test/java/com/shop/mall/service/ReviewServiceTest.java
Labels: 🤝 파일 병합, 💥 중요합니다

#52 Feature 49
  src/main/java/com/shop/mall/controller/CartController.java
  src/main/java/com/shop/mall/domain/Cart.java
  src/main/java/com/shop/mall/dto/CartRequestDto.java
  src/main/java/com/shop/mall/dto/CartResponseDto.java
  src/main/java/com/shop/mall/service/CartService.java
Labels: 📰 새 파일 생성

#57 [refactor]불필요한 import 주석 제거 및 Product TEST Code 수정
  src/main/java/com/shop/mall/controller/CartController.java
  src/main/java/com/shop/mall/controller/DummyController.java
  src/main/java/com/shop/mall/controller/HealthController.java
  src/main/java/com/shop/mall/controller/MemberController.java
  src/main/java/com/shop/mall/controller/OrdersController.java
  src/main/java/com/shop/mall/controller/ProductController.java
  src/main/java/com/shop/mall/controller/ReviewController.java
  src/main/java/com/shop/mall/domain/Img.java
  src/main/java/com/shop/mall/domain/Member.java
  src/main/java/com/shop/mall/domain/Orders.java
  src/main/java/com/shop/mall/domain/Product.java
  src/main/java/com/shop/mall/domain/Product1.java
  src/main/java/com/shop/mall/dto/ProductResponseDto.java
  src/main/java/com/shop/mall/exception/ErrorCode.java
  src/main/java/com/shop/mall/exception/ErrorCodeExceptionHandler.java
  src/main/java/com/shop/mall/repository/Cart/CartRepository.java
  src/main/java/com/shop/mall/repository/Cart/CartRepositoryCustom.java
  src/main/java/com/shop/mall/repository/Cart/CartRepositoryImpl.java
  src/main/java/com/shop/mall/repository/ImgRepository.java
  src/main/java/com/shop/mall/repository/OrdersRepository.java
  src/main/java/com/shop/mall/repository/Product/ProductRepository.java
  src/main/java/com/shop/mall/repository/Product/ProductRepositoryImpl.java
  src/main/java/com/shop/mall/service/CartService.java
  src/main/java/com/shop/mall/service/MemberService.java
  src/main/java/com/shop/mall/service/OrdersService.java
  src/main/java/com/shop/mall/service/ProductService.java
  src/main/java/com/shop/mall/service/ReviewService.java
  src/main/java/com/shop/mall/validator/CartValidator.java
  src/main/resources/static/index.html
  src/test/java/com/shop/mall/domain/MemberTest.java
  src/test/java/com/shop/mall/service/CartServiceTest.java
  src/test/java/com/shop/mall/service/OrdersServiceTest.java
  src/test/java/com/shop/mall/service/ProductServiceTest.java
  src/test/java/com/shop/mall/service/ReviewServiceTest.java
Labels: 🎨 코드 개선, 📝 사소한 코드 변경, 🔥 코드 또는 파일 제거

#61 redis 사용하여 캐싱 완료
  build.gradle
  src/main/java/com/shop/mall/ShoppingApplication.java
  src/main/java/com/shop/mall/controller/ProductController.java
  src/main/java/com/shop/mall/dto/ProductResponseDto.java
  src/main/resources/application.properties
Labels: 🐎 성능 향상, 📝 사소한 코드 변경
